namePrefix: simpleapi-

commonLabels:
  env: production
  provider: kustomize

namespace: simpleapi

generatorOptions: {}

configMapGenerator:
  - behavior: merge
    envs:
      - application.env
    name: carbonite-env

images:
  - name: ghcr.io/florianbgt/simpleapi
    newTag: 23e905de5b09c02aa3d0860412316706a434fbaf

resources:
  - ../../base

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
