apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: application
      component: simpleapi
  template:
    metadata:
      labels:
        app: application
        component: simpleapi
    spec:
      imagePullSecrets:
        - name: dockerconfigjson
      containers:
        - name: api
          image: "ghcr.io/florianbgt/simpleapi"
          resources:
            limits:
              memory: 384Mi # 2 workers + 1 * UWSGI_RELOAD_ON_RSS=128
              cpu: 100m
            requests:
              memory: 256Mi # 2 workers * UWSGI_RELOAD_ON_RSS=128
              cpu: 50m
          ports:
            - name: simpleapi
              containerPort: 3000

          livenessProbe:
            httpGet:
              path: /liveness
              port: simpleapi
          startupProbe:
            httpGet:
              path: /readiness
              port: simpleapi
            failureThreshold: 6
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: env
