apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapi-deployment
spec:
  selector:
    matchLabels:
      app: simpleapi
  template:
    metadata:
      labels:
        app: simpleapi
    spec:
      containers:
        - name: simpleapi
          image: "ghcr.io/florianbgt/simpleapi"
          ports:
            - name: http
              containerPort: 5000
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
          startupProbe:
            httpGet:
              path: /readiness
              port: http
            failureThreshold: 6
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: env
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-url-secret
                  key: dbUrl
            - name: DB_REPLICA_URL
              valueFrom:
                secretKeyRef:
                  name: db-url-secret
                  key: dbReplicaUrl
