apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapi-deployment
spec:
  selector:
    matchLabels:
      app: simpleapi
  template:
    metadata:
      labels:
        app: simpleapi
    spec:
      containers:
        - name: simpleapi
          image: "ghcr.io/florianbgt/simpleapi"
          ports:
            - name: http
              containerPort: 3000
          # resources:
          #   limits:
          #     memory: 384Mi # 2 workers + 1 * UWSGI_RELOAD_ON_RSS=128
          #     cpu: 100m
          #   requests:
          #     memory: 256Mi # 2 workers * UWSGI_RELOAD_ON_RSS=128
          #     cpu: 50m
          # livenessProbe:
          #   httpGet:
          #     path: /liveness
          #     port: api
          # startupProbe:
          #   httpGet:
          #     path: /readiness
          #     port: api
          #   failureThreshold: 6
          #   periodSeconds: 10
          envFrom:
            - configMapRef:
                name: env
