commonLabels:
  provider: kustomize
  app: simpleapi

namespace: apps-ns

images:
  - name: ghcr.io/florianbgt/simpleapi
    newTag: 6bab287232ca17b07237e8ee0a46976453354eda

resources:
  - deployment.yml
  - service.yml
