name: Deploy service using NanoAPI
"on":
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy service using NanoAPI
      uses: Nano-API/Deploy@version/1
      with:
        apiKey: ${{ secrets.NANO_API_TEST_TOKEN }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        stackName: simpleapi1
