name: Deploy service using NanoAPI
"on":
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Nano-API Deploy
        uses: Nano-API/Deploy@version/1
        with:
          apiKey: ${{ secrets.NANO_API_TEST_TOKEN }}
          stackName: simpleapi1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
